name = "signup-worker"
main = "signup-worker/worker.js"
compatibility_date = "2023-01-01"

[vars]
NOTIFICATION_EMAIL = "your@email.com"
GOOGLE_SHEET_ID = "your-sheet-id"
GOOGLE_SERVICE_ACCOUNT_EMAIL = "your-service-account@project.iam.gserviceaccount.com"

# Add these secrets using wrangler:
# wrangler secret put TURNSTILE_SECRET
# wrangler secret put GOOGLE_PRIVATE_KEY
# wrangler secret put SENDGRID_API_KEY
