# Root wrangler.toml (wrangler v3.88.0^)

[env.signup]
name = "signup-worker"
main = "signup-worker/worker.js"
compatibility_date = "2024-01-01"

# Add routes for signup worker
[[env.signup.routes]]
pattern = "encyclopediae.org/signup*"
zone_name = "encyclopediae.org"

[env.signup.vars]
GOOGLE_SHEET_ID = "15JGiLaUTWdV5nyoXNmTJA42GnegQdaARNM4Dnk_flMk"
GOOGLE_SERVICE_ACCOUNT_EMAIL = "encyclopediae-sheets@encyclopediae-initiative.iam.gserviceaccount.com"

[[env.signup.kv_namespaces]]
binding = "SIGNUPS"
id = "2f13b43b3d4a41e89973a2ca7204b626"

[observability.logs]
enabled = true
